# Generated by Django 3.0.5 on 2020-04-27 01:07

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('phone_alt', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('street_two', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('mc', models.CharField(blank=True, max_length=64, null=True)),
                ('dot', models.CharField(blank=True, max_length=64, null=True)),
                ('w9', models.FileField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('street_two', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('phone_alt', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('tax_id', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('phone_alt', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('mc', models.CharField(blank=True, max_length=64, null=True)),
                ('dot', models.CharField(blank=True, max_length=64, null=True)),
                ('w9', models.FileField(blank=True, null=True, upload_to='')),
                ('truck_number', models.IntegerField(blank=True, null=True)),
                ('trailer', models.CharField(blank=True, choices=[('DV', 'Dry Van'), ('FB', 'Flatbed'), ('RF', 'Reefer'), ('CT', 'Conestoga'), ('SD', 'StepDeck'), ('OT', 'Other')], max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('Carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdm.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('IT', 'In transit'), ('OP', 'Open'), ('PU', 'Picked up'), ('DL', 'Delivered'), ('IV', 'Invoiced'), ('CL', 'Closed'), ('MS', 'Missing')], max_length=64, null=True)),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('driver_rate', models.FloatField(blank=True, null=True)),
                ('miles', models.FloatField(blank=True, null=True)),
                ('tarp_fee', models.FloatField(blank=True, null=True)),
                ('detention', models.FloatField(blank=True, null=True)),
                ('additional', models.FloatField(blank=True, null=True)),
                ('rate_confirmation', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='')),
                ('pickup_street', models.CharField(blank=True, max_length=64, null=True)),
                ('pickup_street_two', models.CharField(blank=True, max_length=64, null=True)),
                ('pickup_city', models.CharField(blank=True, max_length=64, null=True)),
                ('pickup_state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('pickup_zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('delivery_street', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_street_two', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('delivery_zipcode', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdm.Carrier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdm.Customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdm.Driver')),
            ],
        ),
    ]
