# Generated by Django 2.2.7 on 2019-11-19 06:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(blank=True)),
                ('pickup_time', models.DateTimeField(blank=True)),
                ('delivery_time', models.DateTimeField(blank=True)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('commodity', models.CharField(blank=True, max_length=64)),
                ('weight', models.FloatField(blank=True)),
                ('driver_rate', models.FloatField(blank=True)),
                ('miles', models.FloatField(blank=True)),
                ('tarp_fee', models.FloatField(blank=True)),
                ('detention', models.FloatField(blank=True)),
                ('additional', models.FloatField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.FileField(blank=True, upload_to='')),
                ('driver_settlement', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('phone_alt', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('mc', models.CharField(blank=True, max_length=64)),
                ('dot', models.CharField(blank=True, max_length=64)),
                ('w9', models.FileField(blank=True, upload_to='')),
                ('truck_number', models.IntegerField(blank=True)),
                ('trailer', models.CharField(blank=True, max_length=64)),
                ('loads', models.ManyToManyField(to='tdm.Load')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=64)),
                ('contact_name', models.CharField(blank=True, max_length=64)),
                ('street', models.CharField(blank=True, max_length=64)),
                ('street_two', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=64)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('phone_alt', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('loads', models.ManyToManyField(to='tdm.Load')),
            ],
        ),
    ]
