# Generated by Django 2.2.7 on 2019-11-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
